name: Packagist Deploy

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: mnavarrocarter/packagist-update@v1.0.0
        with:
          username: "GautierDele"
          api_token: ${{ secrets.PACKAGIST_TOKEN }}